# Generated by Django 3.0.1 on 2020-01-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gezi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_id',
        ),
    ]
